food = ["apple", "cocount","banana"]
print(food)
print(food[0])
food[1] = "peach"
print(food)
food.append(True)
print(food)
food.extend("string")
print(food)
food.extend(["string", 2])
print(food)
food.remove("apple")
print(food)
print("peach" in food)
print(food[0:2])
print(food[0:2:2])
